### PR TITLE
Add Dark mode support to listings and also fix functionality to next/previous buttons

### LINKED ISSUE #251: Listings look odd when in dark mode
image

### PR DESCRIPTION
**Pull request by chennisden**
Resolves #251 

The commit messages are self-explanatory.

> commit 99700aea2ce14c72aa2f486d2f22fe27304565bb
> Author: Dennis Chen <dchen@mathadvance.org>
> Date:   Mon Aug 5 17:31:03 2024 -0700
>
>     Add dark variants for Previous/Next buttons
>
> commit cc72a0c8f6b9125b2aea2a0d358f7c50a3c7e741
> Author: Dennis Chen <dchen@mathadvance.org>
> Date:   Mon Aug 5 17:21:12 2024 -0700
>
>     Fix Listings button functionality
>
>     - the previous and next buttons took people to /browse/PAGENUMBER rather
>       than /browse/?page=PAGENUMBER, where the frontend expects the latter.
>       Fixed.
>     - having fixed that, when we go to a new page, the listings do not
>       refresh because the useEffect calling handleSearch has never been
>       called; the useEffect hook now updates when pageNumber changes.
>
> commit 3c6f3fa793d2848fd3b38f717ed3fdbb513c522e
> Author: Dennis Chen <dchen@mathadvance.org>
> Date:   Mon Aug 5 17:20:50 2024 -0700
>
>     Make previous/next buttons on left/right of screen
>
> commit 7f72c077bae68e77252b34da0c244c884b837e9c
> Author: Dennis Chen <dchen@mathadvance.org>
> Date:   Mon Aug 5 17:09:52 2024 -0700
>
>     Make dark mode version of ListingGridCard
>
>     It may not be a bad idea to
>
>     - add a placeholder image/text when none is present for a listing (even
>       something as simple as "No Image" to make it clear that this was
>       intentional from the part of the listing creator, and not a network
>       error)
>     - remove the `animate-pulse` effect in dark mode; I hesitantly kept it
>       in for now but it is plausible that animate-pulse loses its magic in
>       dark mode.

### CODE REVIEW

**Comment by chennisden** [comment]
The GitHub action history is a bit of a mess because I screwed up rebasing. All is good now.

Here's a screenshot.
image

Before:
image

File: frontend/src/components/Image.tsx [hunk 1]
```diff
@@ -1,8 +1,6 @@
 const Image = () => {
   return (
-    <div>
-      <div className="animate-pulse bg-gray-200 w-full aspect-square"></div>
-    </div>
+    <div className="animate-pulse bg-gray-200 dark:bg-gray-800 w-full aspect-square" />
```
Comment (codekansas) [inline frontend/src/components/Image.tsx:3]: i think there was a reason i wasn't doing this

**Comment by codekansas** [comment]
why does the image in your screenshot look messed up?

File: frontend/src/components/Image.tsx (hunk 1 above)
Comment (chennisden) [reply frontend/src/components/Image.tsx:3]: I'm going to assume it's because backgrounds might be white

**Comment by chennisden** [comment]
> why does the image in your screenshot look messed up?

Fixed in a separate PR. This is a pre existing issue

File: frontend/src/components/Image.tsx (hunk 1 above)
Comment (chennisden) [reply frontend/src/components/Image.tsx:3]: I think either way dark mode listings is going to look a little silly; it's just a question of which looks more silly. A question of personal taste, I suppose.

Comment (chennisden) [reply frontend/src/components/Image.tsx:3]: With #261 I think this is by far the right thing to do.

**Review by codekansas — APPROVED** [review]

**Review by codekansas — APPROVED** [review]
